# Generated by Django 4.0 on 2021-12-28 15:47

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to=shop.models.image_upload_path),
            preserve_default=False,
        ),
    ]
